charity/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from home import urls
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(    
    path(_('admin/'), admin.site.urls),
    path('', include('home.urls')),
)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views 
from django.utils.translation import gettext_lazy as _


app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='home'),
    path(_('events/'), views.events_page, name='events'),
    path(_('story/<slug:slug>/'), views.story_detail, name='detail'),
    path(_('topstory/<slug:slug>/'), views.topstories, name='topstory'),
    path(_('ad/<slug:slug>/'), views.advert, name='advert'),
    path(_('about/'), views.about_page, name='about'),
    path(_('profiles/'), views.profile_feed, name='profiles'),
    path(_('profile/<slug:slug>/'), views.profile_page, name='profile'),
    path(_('donate/'), views.donation_page, name='donate'),
    path(_('receipt/'), views.receipt, name='receipt'),
]

home/models.py
from django.db import models
from django.db.models.deletion import CASCADE


# Create your models here.

# Email Modelform to map to database for receiving email from users
class Email(models.Model):
	email = models.EmailField(unique=True)

	def __str__(self):
		return self.email

# The profiles database Model to map to database
class Profile(models.Model):
	profile_cover_photo = models.ImageField(default = 'profile/profile_cover_photos/profile-photo.png', blank = True, upload_to = 'profile/profile_cover_photos/')
	profile_photo = models.ImageField(default = 'profile/profile_photos/profile-photo.png', blank = True, upload_to = 'profile/profile_photos/')
	first_name = models.CharField(max_length = 14)
	last_name = models.CharField(max_length = 14)
	slug = models.SlugField()
	about_snippet = models.CharField(max_length = 120)
	followers = models.IntegerField(default = 1, blank = True)
	events = models.IntegerField(default = 0, blank = True)
	donations = models.IntegerField(default = 0, blank = True)
	address_field = models.CharField(max_length = 40, blank = True)
	mobile_contact = models.PositiveBigIntegerField(blank = True)
	email = models.EmailField(blank = True)
	facebook_contact = models.CharField(max_length = 20, blank = True)
	twitter_contact = models.CharField(max_length = 20, blank = True)
	about = models.TextField()
	date = models.DateField()

	def __str__(self):
		return self.slug

# followers email collector database table
class Followers_email(models.Model):
	profile = models.ForeignKey(Profile, on_delete=CASCADE)
	email = models.EmailField(unique=True, blank=True)
	
	def __str__(self):
		return self.profile.slug
	
# Profiles Event_photos database Model to map to database. This inherits from Profile and attaches here using foreignkey
class Profile_event_photo(models.Model):
	profile = models.ForeignKey(Profile, on_delete = models.CASCADE)
	event_photos = models.ImageField(blank = True, upload_to = 'profile/events_images/', default = 'profile/events_images/photos-gallery icon.png')

	def __str__(self):
		return self.profile.slug

# News database Model to map to database
class Headline(models.Model):
	title = models.CharField(max_length = 40)
	image = models.ImageField(default = 'news-images/photos-gallery icon.png', upload_to = 'news-images/')
	slug = models.SlugField()
	story_snippet = models.CharField(max_length = 160)
	story = models.TextField()
	date = models.DateTimeField()

	def __str__(self):
		return self.title

#  Flash messages database Model 
class Advert(models.Model):
	title = models.CharField(max_length=120)
	first_message = models.CharField(max_length=250)
	body = models.TextField()
	slug = models.SlugField()
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

# Advert photos database Model to map to database. This inherits from Advert and attaches here using foreignkey
class Advert_image(models.Model):
	advert = models.ForeignKey(Advert, on_delete=CASCADE)
	photos = models.ImageField(upload_to='news-images/', blank=True)

	def __str__(self):
		return self.advert.slug

# Motivational messages
class Topstory(models.Model):
	title = models.CharField(max_length=120)
	body = models.TextField()
	slug = models.SlugField()
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

	def snippet(self):
		return self.body [:450]

# Motivational messages photos database Model to map to database. This inherits from Topstory and attaches here using foreignkey
class Topstory_image(models.Model):
	story = models.ForeignKey(Topstory, on_delete=CASCADE)
	photos = models.ImageField(upload_to='news-images/', blank=True)

	def __str__(self):
		return self.story.slug

home/forms.py
from django.forms import ModelForm
from .models import Email, Followers_email
from django.utils.translation import gettext as _

class Form(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label=''
        self.fields['email'].widget.attrs.update({
            'class': 'email', 
            'placeholder': _('Enter Your Email Here...'),
            })
    class Meta:
        model = Email
        fields = '__all__'


class Followers_email_form(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label=''
        self.fields['email'].widget.attrs.update({
            'class': 'email', 
            'placeholder': _('Enter Your Email Here...'),
            })
        self.fields['profile'].label=''
        self.fields['profile'].widget.attrs.update({
            'class': 'profile'
        })
    class Meta:
        model = Followers_email
        fields = '__all__'

home/views.py
from django.shortcuts import render
from .forms import Followers_email_form, Form
from .models import *
from django.contrib import messages 
from django.core.paginator import Paginator
from django.utils.translation import gettext as _

# Create your views here.

def home_page(request, *args, **kwargs):
	form = Form(auto_id=False)
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			form.clean()
			form.save()
			messages.success(request, _("Your email was received successfully!"), fail_silently = True)
			form = Form()
	else:
		form = Form()
	context = {
		'form': form
	}
	return render(request, './home/home.html', context)


def events_page(request, *args, **kwargs):
	events_objects = Headline.objects.all().order_by('-date')
	Advert_objects = Advert.objects.all().order_by('-date')
	Topstory_objects = Topstory.objects.all().order_by('-date')

	paginate_events = Paginator(object_list=events_objects, per_page=4, orphans=2, allow_empty_first_page=True)
	paginate_advert = Paginator(object_list=Advert_objects, per_page=1, allow_empty_first_page=True)
	paginate_topstory = Paginator(object_list=Topstory_objects, per_page=1, allow_empty_first_page=True)

	page=request.GET.get('page')
	events=paginate_events.get_page(page)
	advert=paginate_advert.get_page(page)
	topstory=paginate_topstory.get_page(page)

	form = Form(auto_id=False)
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			form.clean()
			form.save()
			messages.success(request, _("Your email was received successfully!"), fail_silently = True)
			form = Form()
	else:
		form = Form()

	context = {
		'form': form,
		'events': events,
		'advert': advert,
		'topstory': topstory
	}
	return render(request, './home/events.html', context)


def story_detail(request, slug, *args, **kwargs):
	story = Headline.objects.get(slug = slug)
	form = Form(auto_id=False)
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			form.clean()
			form.save()
			messages.success(request, _("Your email was received successfully!"), fail_silently = True)
			form = Form()
	else:
		form = Form()
	context = {
		'form': form,
		'story': story
	}
	return render(request, './home/story.html', context)


def topstories(request, slug, *args, **kwargs):
	topstory = Topstory.objects.get(slug=slug)
	topstory_images = Topstory_image.objects.filter(story=topstory)
	form = Form(auto_id=False)
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			form.clean()
			form.save()
			messages.success(request, _("Your email was received successfully!"), fail_silently = True)
			form = Form()
	else:
		form = Form()
	context = {
		'form': form,
		'topstory': topstory,
		'topstory_images': topstory_images
	}
	return render(request, './home/topstories.html', context)


def advert(request, slug, *args, **kwargs):
	advert = Advert.objects.get(slug=slug)
	advert_images = Advert_image.objects.filter(advert=advert)
	form = Form(auto_id=False)
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			form.clean()
			form.save()
			messages.success(request, _("Your email was received successfully!"), fail_silently = True)
			form = Form()
	else:
		form = Form()
	context = {
		'form': form,
		'advert': advert,
		'advert_images': advert_images
	}
	return render(request, './home/advert.html', context)


def about_page(request, *args, **kwargs):
	form = Form(auto_id=False)
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			form.clean()
			form.save()
			messages.success(request, _("Your email was received successfully!"), fail_silently = True)
			form = Form()
	else:
		form = Form()
	context = {
		'form': form
	}
	return render(request, './home/about.html', context)


def profile_feed(request, *args, **kwargs):
	profiles = Profile.objects.all().order_by("-date")
	form = Form(auto_id=False)
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			form.clean()
			form.save()
			messages.success(request, _("Your email was received successfully!"), fail_silently = True)
			form = Form()
	else:
		form = Form()
	context = {
		'profiles': profiles,
		'form': form
	}
	return render(request, './home/profile_feed.html', context)


def profile_page(request, slug, *args, **kwargs):
	profiles = Profile.objects.get(slug=slug)
	event_photos = Profile_event_photo.objects.filter(profile=profiles)
	form = Form(auto_id=False)
	data={
		'profile' : profiles,
	}
	followers_email_form = Followers_email_form(request.POST or None, initial=data, auto_id=False)

	if request.method == 'POST' and "followers" in request.POST:
			if followers_email_form.is_valid():
				followers_email_form.clean()
				followers_email_form.save()
				profiles.followers += 1
				profiles.save()
				messages.success(request, _("Your email was received successfully!, You now follow ")+ profiles.first_name + _("'s updates"), fail_silently=True)
				followers_email_form = Followers_email_form()
			else:
				followers_email_form = Followers_email_form()

	if request.method == 'POST' and "subscription_email" in request.POST:
			form = Form(request.POST)
			if form.is_valid():
				form.clean()
				form.save()
				messages.success(request, _("Your email was received successfully!"), fail_silently = True)
				form = Form()
			else:
				form = Form()

	
	context = {
		'profiles': profiles,
		'event_photos': event_photos,
		'form': form,
		'followers_email_form': followers_email_form
	}
	return render(request, './home/profile.html', context)


def donation_page(request, *args, **kwargs):
	form = Form(auto_id=False)
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			form.clean()
			form.save()
			messages.success(request, _("Your email was received successfully!"), fail_silently = True)
			form = Form()
	else:
		form = Form()
	context = {
		'form': form
	}
	return render(request, './home/donate.html', context)


def receipt(request, *args, **kwarg):
	form = Form(auto_id=False)
	if request.method == 'POST':
		form = Form(request.POST)
		if form.is_valid():
			form.clean()
			form.save()
			messages.success(request, _("Your email was received successfully!"), fail_silently = True)
			form = Form()
	else:
		form = Form()
	context = {
		'form': form
	}
	return render(request, 'home/receipt.html', context)

home/templates/home/about.html
{% extends './base.html' %}
{% block body %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './Css/about.css' %}">
    <title>{% trans "about" %}</title>
</head>
<body>
    <section class="msg1">
        <div class="card1" data-aos="zoom-in" data-aos-duration="1400" data-aos-easing="ease">
            <h3 id="about-us">{% translate "ABOUT US" %}</h3>
        </div>
        <div class="card2" data-aos="fade-left" data-aos-duration="1500" data-aos-easing="ease">
            <p class="about-us-msg">
                {% blocktranslate %}
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quidem commodi rerum pariatur, distinctio temporibus, 
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem sit corrupti est perspiciatis 
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Officiis error maiores itaque nemo, expedita assumenda ea eligendi
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt quaerat harum alias ea soluta.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Commodi, ratione! Eum dignissimos omnis iusto nostrum perferendis.
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione, odit obcaecati dignissimos, sunt non quo recusandae
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore voluptatem aliquam reprehenderit, delectus, ullam
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quas, voluptates dolorem? Totam sunt repellat a beatae
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem minima, accusamus adipisci nam quam unde maiores autem. Voluptas
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Asperiores nemo expedita amet voluptates accusamus laudantium vitae! Officia repellat
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem, praesentium, atque quae ducimus amet, inventore sequi
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt enim laudantium atque delectus eaque cupiditate, beatae voluptatibus? Nam
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem voluptatum saepe delectus a ipsam. Unde possimus doloribus
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium aliquam quam molestias earum. Eius dolores, aliquid corrupti qui 
                animi eum fugit veritatis pariatur consequuntur voluptatum magni laudantium, non veniam quidem. enim animi veritatis labore id officia, adipisci odio accusamus ipsam doloremque nam aliquam? qui cum explicabo. Suscipit, eum! Accusantium, laborum illo necessitatibus nemo corrupti eveniet. maiores expedita nobis doloribus accusamus. Voluptas, dolore iusto provident veniam eaque totam impedit ex. tenetur mollitia minus repellendus dolores saepe recusandae. Exercitationem tenetur blanditiis unde eligendi! dolores quos reprehenderit praesentium exercitationem eveniet deserunt a ducimus sint. Velit, accusantium. itaque, animi vero natus vitae id assumenda quae ipsam ullam debitis adipisci dolore officiis. eos incidunt non deleniti unde ea consequuntur quaerat voluptas? Sequi eligendi aut voluptatem porro enim totam! magni commodi nulla suscipit voluptate consectetur possimus sint nihil dicta minima quibusdam velit provident. Iste earum aliquid fuga, maxime commodi ipsam inventore quia asperiores praesentium necessitatibus labore! Quas? Explicabo deserunt, pariatur a optio velit odit quidem, maxime quasi modi delectus harum ipsa possimus alias! rem blanditiis tempore consequatur, asperiores, nostrum omnis facilis dolorum mollitia totam quasi beatae. dignissimos expedita illo officia quidem soluta vel debitis nisi modi explicabo ut, a quo suscipit in veritatis. ipsum exercitationem eligendi iure ea repellat quae ipsam obcaecati atque rem sed consectetur saepe animi quos?
                {% endblocktranslate %}
            </p>
        </div>
    </section>
    <section class="licence">
        <h3 id="licence">{% translate "L&D LICENCE" %}</h3>
        <p class="licence-body">
            {% blocktranslate %}
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde recusandae quam totam sapiente vitae delectus? 
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam delectus magni amet officia alias minima mollitia ratione soluta
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum exercitationem ipsam doloremque iusto quia
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur velit, nisi cum consequuntur explicabo numquam, expedita
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ut beatae, excepturi animi nisi repellat sequi atque
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, quam tempora voluptatem quibusdam sunt quas ad itaque
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum maxime eius accusamus? Odio nostrum expedita quas exercitationem,
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum iste ea cumque. Incidunt, id ratione. Labore fugiat harum doloremque,
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, aspernatur. At doloremque distinctio officia tempore possimus
            iste illum soluta aliquid aut tempora quod ad assumenda quos, ea consequuntur nulla dolores! porro soluta ab deserunt, velit eos consequuntur repellendus esse expedita at. nihil voluptatum quasi minus nulla inventore corporis incidunt vero voluptatibus praesentium perferendis non! in unde facilis fugit dolorum, beatae assumenda quae veniam ducimus illo totam vero. officia dolor quam harum modi incidunt! Ullam quisquam beatae dignissimos veritatis culpa veniam! eius delectus fugiat, amet voluptatum doloremque vel officiis doloribus porro reiciendis maiores quis inventore. fugit ducimus, mollitia nulla quidem vel numquam debitis sapiente praesentium iste eum quis et consequatur quas! numquam autem, necessitatibus, suscipit quis voluptatem totam obcaecati. Qui consequuntur repudiandae molestias. Officia fugiat ut nobis? Sed nisi, rerum iure deleniti nulla voluptates cupiditate architecto amet natus!
            {% endblocktranslate %}
        </p>
    </section>
</body>
</html>
{% endblock %}

home/templates/home/advert.html
{% extends "home/topstories_extension.html" %}
{% load static %}
{% block title_head %}{{ advert.title }}{% endblock %}
{% block story %}{{ advert.body }}{% endblock %}
{% block images %}{% for advert_images in advert_images%}<img src="{{advert_images.photos.url}}" alt="">{% endfor %}{% endblock %}

home/templates/home/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './Css/base.css' %}">
    <link rel="stylesheet" href="{% static './Js/aos-master/dist/aos.css' %}">
    <script src="{% static './Js/aos-master/dist/aos.js' %}"></script>
</head>
<body>
    <header>
        <img id="menu-icon" src="{% static './images/menu icon.png' %}" alt="">
        <ul id="dropdown">
            <img src="{% static './images/close.png' %}" alt="" id="close">
            <li><a href="{% url 'home:home' %}">{% translate "HOME" %}</a></li>
            <li><a href="{% url 'home:events' %}">{% translate "EVENTS" %}</a></li>
            <li><a href="{% url 'home:about' %}">{% translate "ABOUT" %}</a></li>
            <li>{% translate "CONTACT" %}</li>
            <li id="language1">{% translate "LANGUAGE" %}</li>
            <li><a href="{% url 'home:profiles' %}">{% translate "PROFILES" %}</a></li>
        </ul>
        <div class="container">
            <div class="language-form">
                <form action="{% url 'set_language' %}" method="post" class="language-switch">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ redirect_to }}">
                    <label for="language" class="language">{% translate "To change your language, select from the list provided" %}</label>
                    <select name="language" id="language">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages%}
                        {% for language in languages %}
                            <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}selected{% endif %}>
                                {{ language.name_local}} "{{ language.code }}" 
                            </option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="CHANGE">
                    <button class="cancel">CANCEL</button>
                </form>
            </div>
            <nav class="navbar">
                <figure class="logo-img">
                    <img id="logo" src="{% static './images/charity logo.png' %}" alt="logo">
                </figure>
                <ul id="menu">
                    <li><a href="{% url 'home:home' %}">{% translate "HOME" %}</a></li>
                    <li><a href="{% url 'home:events' %}">{% translate "EVENTS" %}</a></li>
                    <li><a href="{% url 'home:about' %}">{% translate "ABOUT" %}</a></li>
                    <li>{% translate "CONTACT" %}</li>
                    <li id="language2">{% translate "LANGUAGE" %}</li>
                    <li><a href="{% url 'home:profiles' %}">{% translate "PROFILES" %}</a></li>
                </ul>
            </nav>
            <div id="donate-btn">
                <button><a href="{% url 'home:donate' %}">{% translate "Donate" %}</a></button>
            </div>
        </div>
    </header>
    {% if messages %}
    <ul class="messages">
        {% for messages in messages %}
        <li {% if messages.tags %} class="{{ messages.tags }}" {% endif%}>{{ messages }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% block body %}

    {% endblock %}
    <footer class="footer">
		<div class="container2">
			<h2 class="about-us"><a href="{% url 'home:about' %}">{% trans "About Us" %}</a><br>{% trans "Contact" %} <br>{% trans "Terms & Conditions" %}</h2>
			<h2 class="social_media_addresses"><img src="{% static './images/white_facebook_icon.png' %}" alt=""> {% trans "Facebook" %} <br><img src="{% static './images/white_twitter_icon.png' %}" alt=""> {% trans "Twitter" %} <br><img src="{% static './images/instagram_icon.png' %}" alt=""> {% trans "Instagram" %}</h2>
			<h2 class="address">497 Evergreen Rd. Roseville, CA 95673 <br>+44 345 678 903 <br>adobexd@mail.com</h2>
		</div>
		<div class="container3">
			<h2 class="newsletter">{% trans "Subscribe to our newsletter" %}</h2>
			<div class="email">
				<form action="" method="POST" class="email">
                    {% csrf_token %}
                    {{ form }}
					<button class="email"><input type="submit" name="subscription_email" placeholder="Submit"></button>
				</form>
			</div>
		</div>
	</footer>
</body>
<script src="{% static './Js/base.js' %}"></script>
</html>

home/templates/home/events.html
{% extends "home/base.html" %}
{% load static %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>events</title>
	<link rel="stylesheet" type="text/css" href="{% static './Css/events.css' %}">
</head>
<body>
	<section class="msg1">
		<div class="wrapper">
			<h3 class="float msg">we are having issues with our online services right now please bear with us!</h3>
		</div>
		{% for advert in advert%}
		<div class="card1" data-aos="zoom-in" data-aos-duration="1300" data-aos-easing="ease">
			<h3 class="card1-msg"><a class="title" href="{% url 'home:advert' slug=advert.slug %}">{{ advert.first_message }}</a></h3>
		</div>
		{% endfor %}
		<div class="card2">
			<h4 class="card2-msg float">Asia's giant western grant is acquiring mother love 'enteron' and will now be handling her affairs</h4>
		</div>
	</section>
	<section class="msg2">
		<div class="container">
			{% for events in events %}
			<div class="card" data-aos="fade-up-left" data-aos-duration="700" data-aos-easing="ease">
				<img class="card-img" src="{{ events.image.url }}" alt="">
				<div class="wrapper">
					<h4 class="card-msg1"><a class="title" href="{% url 'home:detail' slug=events.slug %}">{{ events.title }}</a></h4>
					<p class="card-msg2">{{ events.story_snippet }}<span><a class="link" href="{% url 'home:detail' slug=events.slug %}"> see more...</a></span></p>
				</div>			
			</div>
			{% endfor %}
		</div>	
	</section>
	<section class="msg3">
		{% for topstory in topstory %}
		<div class="card" data-aos="zoom-in" data-aos-duration="1300" data-aos-easing="ease">
			<h4 class="card-msg"><a href="{% url 'home:topstory' slug=topstory.slug %}" class="title">{{ topstory.snippet }} <span>see more...</span></a></h4>
		</div>
		{% endfor %}
		<h3 class="float msg">No matter the position you are in right now just remember this..."you are the strongest of your form that could ever exist and you will get through this!</h3>
	</section>
	<div class="page-links">
		<span class="step-links">
			{% if events.has_previous %}
				<a href="?page=1">&laquo; first</a>
				<a href="?page={{events.previous_page_number }}">previous</a>
			{% endif %}
			<span class="current">
				page {{ events.number }} of {{ events.paginator.num_pages }}
			</span>
			{% if events.has_next %}
				<a href="?page={{ events.next_page_number }}">next</a>
				<a href="?page={{events.paginator.num_pages }}">last &raquo;</a>
			{% endif %}
		</span>
	</div>
</body>
</html>
{% endblock %}

home/templates/home/profile_feed.html
{% extends './base.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './Css/profile_feed.css' %}">
    <title>profiles</title>
</head>
<body>
    <section class="grid">
        <div id="search" data-aos="zoom-in" data-aos-duration="1400" data-aos-easing="ease">
            <input id="search-bar" type="text" maxlength="30" placeholder="Search" onkeyup="searchFunction()">
            <img id="search-icon" src="{% static './images/search_icon.png'%}" alt="">
        </div>
        <div class="profile-list">
            <h1 class="no-match">No profiles match your search</h1>
            {% for profiles in profiles %}
            <div class="card1">
                <img src="{{ profiles.profile_photo.url }}" alt=""> 
                <a class="color-link" href="{% url 'home:profile' slug=profiles.slug %}">
                    <div class="container">
                        <h5 class="name">{{ profiles.first_name }} {{ profiles.last_name }}</h5>
                        <div class="about">
                            <h6 class="about">About:</h6>
                            <p class="about-info">{{ profiles.about_snippet }} <span><a class="link" href="{% url 'home:profile' slug=profiles.slug %}"> see more...</a></span></p>
                        </div>
                    </div>
                </a>
                <p class="date">{{ profiles.date }}</p>
            </div>
            {% endfor %}
        </div>
    </section>
    <script src="{% static './Js/profile_feed.js' %}"></script>
</body>
</html>
{% endblock %}